<a href="https://colab.research.google.com/github/shohan12727/TensorFlow/blob/main/expand-dims.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Initialization**

In [ ]:
import tensorflow as tf

### **Main code**

# The tf.expand_dims() function in TensorFlow is used to insert a new dimension (axis) of length 1 into a tensor's shape at a specified position.

**Axis 0**

In [32]:
t1 = tf.constant([1,2,3,4,5,6,7,8,9,10])
tf.expand_dims(t1, axis=0)

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

**Axis 1**

In [33]:
tf.expand_dims(t1, axis=1)

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int32)>