<a href="https://colab.research.google.com/github/shohan12727/TensorFlow/blob/main/learning_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Initialization**

In [ ]:
import tensorflow as tf

### **Main code**

In [18]:
tensor = tf.constant([1,2,3,20,5,8])
tensor.shape

TensorShape([6])

In [20]:
squeezed = tf.squeeze(tensor)
squeezed
squeezed.shape

TensorShape([6])

# *Another example*

In [22]:
t2 = tf.constant([[34,54,65,23,5]])
tf.squeeze(t2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([34, 54, 65, 23,  5], dtype=int32)>

In [26]:
t3 = tf.constant([
    [1,2,3,4],
    [5,6,7,9],
    [5,7,8,90]
])
tf.squeeze(t3)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  9],
       [ 5,  7,  8, 90]], dtype=int32)>

### tf.squeeze() only removes dimensions whose size is exactly 1