<a href="https://colab.research.google.com/github/shohan12727/TensorFlow/blob/main/math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
x = tf.constant([[1,2,4], [3,4,5]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [3, 4, 5]], dtype=int32)>

In [4]:
tf.expand_dims(x, axis=-1)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [4]],

       [[3],
        [4],
        [5]]], dtype=int32)>

In [5]:
tf.expand_dims(x, axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [3, 4, 5]]], dtype=int32)>

In [7]:
y = tf.constant([
    [1,2],
    [3,4]
])
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
y + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [9]:
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
y * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [11]:
y -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [12]:
y / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [14]:
tf.multiply(y, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [15]:
tf.add(y , 30)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 32],
       [33, 34]], dtype=int32)>

In [16]:
y @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [17]:
A = tf.constant([[3,4,5,7], [2,1,4,5]])
A

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 4, 5, 7],
       [2, 1, 4, 5]], dtype=int32)>

In [18]:
tf.transpose(A)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 2],
       [4, 1],
       [5, 4],
       [7, 5]], dtype=int32)>

In [25]:
o = tf.constant([[1, 2, 3],
                 [4, 5, 6]])


In [27]:
sum_all = tf.reduce_sum(o)
print(sum_all)

tf.Tensor(21, shape=(), dtype=int32)
