<a href="https://colab.research.google.com/github/shohan12727/TensorFlow/blob/main/tf-reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Initialization**

In [ ]:
import tensorflow as tf

### **Main code**

### tf.reshape() changes the shape of a tensor without changing its data.

In [28]:
t1 = tf.constant([
    [1,2,3],
    [4,5,6]
])

t1.shape

TensorShape([2, 3])

In [29]:
tf.reshape(t1,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### -1 automatically calculates the dimension needed to maintain total elements

In [30]:
tf.reshape(t1,[-1,1])

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>