<a href="https://colab.research.google.com/github/shohan12727/TensorFlow/blob/main/tf.random.uniform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### tf.random.uniform( )

In [2]:
import tensorflow as tf

In [4]:
t1 = tf.random.uniform(shape=(5,))
t1

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.8223692, 0.7322922, 0.3551576, 0.8399844, 0.907001 ],
      dtype=float32)>

## Can set min value and max value

In [13]:
t2 = tf.random.uniform(shape=(19,), minval=11, maxval=18)
print(t2)

tf.Tensor(
[13.468964 16.271023 11.664518 17.414648 17.066916 16.023407 16.331448
 11.173617 16.795134 16.701916 13.054328 14.813544 12.150784 16.81203
 14.705336 16.794865 14.799715 16.50814  11.563897], shape=(19,), dtype=float32)
