<a href="https://colab.research.google.com/github/shohan12727/TensorFlow/blob/main/tf.random.normal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### tf.random.uniform( )

In [2]:
import tensorflow as tf

In [14]:
t1 = tf.random.normal([3,4])
print(t1)

tf.Tensor(
[[ 1.4010814  -1.2803918   1.0387703   1.5173568 ]
 [-0.8139134  -1.4752105   0.47379985  0.76726377]
 [ 1.8042737   0.43538854  0.27070862 -0.00395662]], shape=(3, 4), dtype=float32)
